[project]
name = "source"
version = "0.1.0"
description = "Add a short description here"
authors = ["Emanuele Giacomini <giacomini@diag.uniroma1.it>"]
channels = ["nvidia/label/cuda-11.8.0","pytorch", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
pip = ">=24.3.1,<24.4"
cuda = ">=11.8.0,<11.9"
pytorch-cuda = ">=11.8,<12"
pytorch = ">=2.5.1,<2.6"
torchvision = ">=0.20.1,<0.21"
gcc = "11.*"
gxx = ">=11.4.0,<15.1"
ninja = ">=1.12.1,<1.13"

[pypi-dependencies]
plyfile = ">=1.1, <2"
opencv-python = ">=4.10.0.84, <4.10.1"
tqdm = ">=4.67.1, <4.68"
# diff-gaussian-rasterization = {path = "./submodules/diff-gaussian-rasterization"}
# fused-ssim = {path = "./submodules/fused-ssim"}
# simple-knn = {path = "./submodules/simple-knn"}


[system-requirements]
cuda = "11"

